# %% [markdown]
# # Classical Electrodynamics

# Electrodynamics is one of the branches of physics dedicated to study one of the four fundamental forces of the universe: The electromagnetic interaction. 

# It has great applications, remarkably in modern days where electricity and magnetic phenomena are the basis of technology.

# ---

# ## 1. Electrostatic Fields of Point Charges

# Having $N$ point charges $Q_i$ fixed at positions in the plane given by the vectors $\vec{r}_i$, $i=1,\ldots, N$. The electric field is given by Coulomb's Law:

# $$\vec{E}(\vec{r})=\frac{1}{4\pi\epsilon_0} \sum_{i=1}^N\dfrac{Q_i}{|\vec{r}-\vec{r}_i|^2} \hat{\rho}_i$$

# where $\hat{\rho}_i=(\vec{r}-\vec{r}_i)/|\vec{r}-\vec{r}_i|$ is the unit vector in the $\vec{r}-\vec{r}_i|$ direction. This field can be split into the components:

# $$\begin{aligned}
#     E_x(x,y)=\dfrac{1}{4\pi\epsilon_0}\sum_{i=1}^N \dfrac{Q_i(x-x_i)}{((x-x_i)^2+(y-y_i)^2)^{3/2}}\\
#     E_y(x,y)=\dfrac{1}{4\pi\epsilon_0}\sum_{i=1}^N \dfrac{Q_i(y-y_i)}{((x-x_i)^2+(y-y_i)^2)^{3/2}}
# \end{aligned}$$

# Furthermore, the field comes from a potential following the next relation:

# $$\vec{E}(\vec{r})=-\vec{\nabla}V(\vec{r})$$

# The electrostatic potential at a point $\vec{r}$ is

# $$V(\vec{r})=V(x,y)= \dfrac{1}{4\pi\epsilon_0} \sum_{i=1}^N \dfrac{Q_i}{((x-x_i)^2+(y-y_i)^2)^{1/2}}$$

# The electric field lines are the integral curves of the vectorial field $\vec{E}$. The electric field's magnitude is proportional to the density of field lines, i.e. the electric flux $\Phi_E=\int_{\mathrm{S}}\vec{E}\cdot d\vec{A}$ through a surface $\mathrm{S}$ is proportional to the number of field lines that cross the surface. The electric field lines of point charge distributions start at positive charges and finish at negative charges or extend to infinity.

# The equipotential surfaces are the union of points in space where the electrostatic potential has fixed values, and are closed surfaces. It can be shown that an intense electric field in a given point is equivalent to a great spatial variation of the electric potential, i.e., a high density of equipotential surfaces. The electric field is perpendicular to the equipotential surfaces at each point, and points in the direction where $V$ decreases.

# ---

# ## 1.2. Electric Dipoles and Quadrupoles

# It has been shown which is the expression that describe the field at each point of space generated by a distribution of N point charges with positions $\vec{r}_i$

# $$\vec{E}(\vec{r})=\frac{1}{4\pi\epsilon_0} \sum_{i=1}^N\dfrac{Q_i}{|\vec{r}-\vec{r}_i|^2} \hat{\rho}_i$$

# Cases of greater practical interest are the dipoles and quadrupoles since these are used in an infinity of situations related with fields in matter and electromagnetic radiation.

# Depending on the charge that the particles making up the dipole have, there are three general configurations.

# ---

# ## Computational Simulation

# To solve the computational problem of finding the equipotential lines, we must discretize the continuous field line through a finite number of small line segments $\Delta l$ in the electric field direction, from which the following components can be derived:

# $$\Delta x=\Delta l\dfrac{E_x}{E} \qquad , \qquad \Delta y=\Delta l\frac{E_y}{E}$$

# where $E$ is the field's magnitude.

# ![](figures/Field_Lines.png)

# To compute the equipotential lines we use the fact that they are perpendicular to the electric field at each point. This tells us that if the field goes in the $(\Delta x,\Delta y)$ direction, the perpendicular direction is $(-\Delta y,\Delta x)$. Therefore, the equipotential lines can be obtained with:

# $$\Delta x=-\Delta l\dfrac{E_y}{E} \qquad , \qquad \Delta y=\Delta l\frac{E_x}{E}$$

# The algorithm to compute this is as follows:

# * 1. Choose an initial point $(x_0, y_0)$ which belongs to a single line to draw.

# * 2. Compute E at that point.

# * 3. Use an small $\Delta l$ and compute $\Delta x$ ans $\Delta y$. 

# * 4. Make a substitution $x \to x + \Delta x$ and $y \to y + \Delta y$. 

# * 5. Repeat until reaching a termination criteria, for example, when a field line reaches a given plotting area or gets to a minimum distance from the charge.

# Following this line of thought, the electric field of point charges is as follows:

# %%
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

def plot_map_phase_space(field: bool = True):
    """
    Plots the phase space map for a given configuration of charges. 
    If field is True, it plots the electric field lines; if False, it plots the equipotential lines.
    """
    sign = 1 if field else -1
    style = "->" if field else "-"
    x, y = np.meshgrid(np.arange(-5., 5., 0.01), np.arange(-5., 5., 0.01))
    xdot, ydot =0, 0
    for i in range(len(xq)):
        norm = np.sqrt((x-xq[i])**2 + (y-yq[i])**2)
        xdot += q[j][i]*(x-xq[i])/(norm**3)
        ydot += sign * q[j][i]*(y-yq[i])/(norm**3)
        if q[j][i]>0:
            circle=plt.Circle((xq[i],yq[i]), 0.2, color='red')
        else:
            circle=plt.Circle((xq[i],yq[i]), 0.2, color='blue')
        ax[j].add_artist(circle)
    if not field:
        tempx = xdot
        xdot = ydot
        ydot = tempx

    ax[j].streamplot(x, y, xdot, ydot, density=1.5, arrowstyle=style)
    ax[j].set_xlabel(r"x")
    ax[j].set_ylabel(r"y")
    ax[j].set_facecolor("black")

n=1
while n<3:
    if n==1:
        fig, ax = plt.subplots(1,2, figsize=(8, 3))
        xq=[0]
        yq=[0]
        q=[[1],[-1]]
        for j in range(2):
            plot_map_phase_space(field = True)
        plt.suptitle("Electric field lines (monopole)")
    elif n==2:
        fig, ax = plt.subplots(1,3, figsize=(12, 3))
        xq=[-2.5,2.5]
        yq=[0,0]
        q=[[1,1],[-1,-1],[1,-1]]
        for j in range(len(q)):
            plot_map_phase_space(field = True)
        plt.suptitle("Electric field lines (dipole)")
    plt.show()
    n+=1

# %%[markdown]
# **Monopole:** This diagram shows the nature of point charges and their role in the direction of fields. As it was mentioned before, field begins at positive charges, i.e., these function as **fonts** of field. On the other hand, fields finish at negative charges, i.e., these have the role of **sinks** of field.

# **Dipole:** For the case in which both charges have the same sign, the fields diverge or crash exactly at half the distance that splits them apart. This is a sign of the repulsive nature of the interaction between charges of the same sign.

# On the other hand, when charges have opposite sign, the field's lines that they generate get united or couple in a certain sense, creating continuous trayectories that born at the positive charge and end at the negative charge. This is a sign of the attractive nature of the interaction between charges of the same sign.

# %%
n=1
while n<3:
    if n==1:
        fig, ax = plt.subplots(1,2, figsize=(8, 3))
        xq=[0]
        yq=[0]
        q=[[1],[-1]]
        for j in range(2):
            plot_map_phase_space(field = False)
        plt.suptitle("Equipotential lines (single charge)")
    elif n==2:
        fig, ax = plt.subplots(1,3, figsize=(12, 3))
        xq=[-2.5,2.5]
        yq=[0,0]
        q=[[1,1],[-1,-1],[1,-1]]
        for j in range(len(q)):
            plot_map_phase_space(field = False)
        plt.suptitle("Equipotential lines (pair charges)")
    plt.show()
    n+=1

# %% [markdown]
# **Monopole:** Where it can be seen that the equipotential lines are exactly the same since the quantities are scalar, they do not point in a certain diraction as the vectors of a field. The only difference is that they have opposite sign.

# **Dipole:** It can be shown that the zones in which the density of equipotential surfaces is greater is where the field will be more intense. In the image to the right it is clear that right at the middle of the distance between the charges, various equipotential lines conflow in a single point, showing the coupling between the charges of the opposite charges.

# %%
fig, axes = plt.subplots(2,2, figsize=(8, 8))

ax = axes.flatten()
xq=[-2.5,-2.5,2.5,2.5]
yq=[2.5,-2.5,-2.5,2.5]
q=[[1,1,1,1],[-1,-1,-1,-1],[1,-1,1,-1],[1,1,-1,-1]]
for j in range(len(q)):
    plot_map_phase_space(field = True)

plt.suptitle("Electric field lines (four charges)")
plt.tight_layout()
plt.show()

# %% [markdown]
# **Cuadrupole:** Here it is shown a behavior similar to that of the dipole. At the first two cases where all of the charges are equal with the same sign, there exist an stable equilibrium point at the geometric center of the quadrupole to which all the field lines tend to go, meanwhile for the negative charges, this point is of instable equilibrium.

# On the other hand, when there are two charges of the same sign and two of the opposite sign, it can be configurated in a way in which each of them forms a kind of dipole with its neighbouring charge. In this scenario the geometric center becomes a saddle point from an stability analysis point of view.

# The last configuration presented is that of two dipoles oriented at the same direction and placed one on top of the other. The inferior and superior sections of the quadrupole seem to interact repulsively since the field lines diverge right at half the distance that separates them. 

# %%
fig, axes = plt.subplots(2,2, figsize=(8, 8))

ax = axes.flatten()
xq=[-2.5,-2.5,2.5,2.5]
yq=[2.5,-2.5,-2.5,2.5]
q=[[1,1,1,1],[-1,-1,-1,-1],[1,-1,1,-1],[1,1,-1,-1]]
for j in range(len(q)):
    plot_map_phase_space(field = False)

plt.suptitle("Equipotential lines (four charges)")
plt.tight_layout()
plt.show()

# %% [markdown]
# ## 1.3. Charged Ring

# The charged ring is a type of system that is conformed by a continuous distribution of charge, which is difficult to model computationally. In this sense, the charge distribution must be discretized into point charges really close together following the path of a ring.

# %%
Nmax = 300
q_unit = 1/Nmax
in_array = np.linspace(-(np.pi), np.pi, Nmax)
xq = np.cos(in_array)
yq = np.sin(in_array)
q = [list(np.ones(Nmax)*q_unit), list(np.ones(Nmax)* -q_unit)]

fig, ax = plt.subplots(1,2, figsize=(8, 4))
for j in range(len(q)):
    plot_map_phase_space(field = True)
plt.suptitle("Electric field lines (four charges)")
plt.tight_layout()
plt.show()

# %%
Nmax = 300
q_unit = 1/Nmax
in_array = np.linspace(-(np.pi), np.pi, Nmax)
xq = np.cos(in_array)
yq = np.sin(in_array)
q = [list(np.ones(Nmax)*q_unit), list(np.ones(Nmax)* -q_unit)]

fig, ax = plt.subplots(1,2, figsize=(8, 4))
for j in range(len(q)):
    plot_map_phase_space(field = False)
plt.suptitle("Equipotential lines (four charges)")
plt.tight_layout()
plt.show()

# %% [markdown]
# ---

# ## 2. Laplace's Equation

# An interesting case to study is at regions in space where there are no electric charges where the differential Gauss' Law takes the shape

# $$\vec{\nabla}\cdot \vec{E}(x,y,z)= \frac{\partial E_x}{\partial x} + \frac{\partial E_y}{\partial y} + \frac{\partial E_z}{\partial z}=0$$

# And it is known that the electric field is the gradient of electric potential. Which indicates that the electric potential obeys Laplace's Equation

# $$\vec{\nabla}^2V = \frac{\partial^2V}{\partial x^2} + \frac{\partial^2V}{\partial y^2} + \frac{\partial^2V}{\partial z^2}=0$$

# Facing a situation that involves Laplace's equation, it is common to know certain frontier conditions for $V$ in a three dimensional surface, either its value or the value of its spatial derivative (electric field). Furthermore, due to the unicity theorem, it is known that by knowing the frontier conditions over a given closed surface for this system, the solution to Laplace's equation is unique and the potential and electric field are determined at each point of space.

# A key difference of these kind of problems is that this differential equation can not be solved with any of the Runge-Kutta methods since it is a partial differential equation. For this case, the **relaxation method** is applied, usefull for partial differential equations known as eliptic equation.

# For this case, the independent variables are discretized in a grid where each point is labeled by the whole numbers $i$, $j$ and $k$. In this way the objective is to determine $V(i,j,k)=V(i\Delta x,j\Delta y, k\Delta z)$. So the partial derivatives can be rewritten as 

# $$\begin{aligned}
#     \frac{\partial^2 V}{\partial x^2} & \approx \frac{1}{\Delta x} \left[\frac{V(i+1, j,k)-V(i,j,k)}{\Delta x}- \frac{V(i,j,k)-V(i-1,j,k)}{\Delta x}\right]\\
#     & \approx \frac{V(i+1, j,k)+V(i-1,j,k) -2V(i,j,k)}{(\Delta x)^2}
# \end{aligned}$$

# This expression is symmetric since it takes a point before and after to compute the derivative, which reduces the computational errors. The other partial derivatives are similar. Replacing in Lapace's equation and solving for $V(i,j,k)$ it is found

# $$\begin{aligned}
#     V(i,j,k)= & \frac{1}{6}[V(i+1,j,k)+V(i-1,j,k) +V(i,j+1,k) \\ & +V(i,j-1,k) +V(i,j,k+1)+V(i,j,k-1)]
# \end{aligned}$$

# where it is assumed that the step size in all directions is the same ($\Delta x=\Delta y=\Delta z$). This tells us that the value of the potential at any point is the average of $V$ over all the neighbouring points. The solution for $V(i,j,k)$ is the function that satisfies this condition simultaneously at all points.

# A way to determine this function assuming that $V$ is known at the frontiers is to take an initial approximation $V_0(i,j,k)$ and use it to compute a new upgraded value $V_1$, which will be used to compute a new value $V_2$, and repeat iteratively until reaching a result that satisfies a convergence criteria. This algorithm is known as Jacobi's method, even though there are other ways to implement the relaxation methods.

# ### 2.1 Electric Potential in a Square box

# Suppose an square box which is infinitely large in both directions of z axis, subject to the following frontier conditions

# ![](figures/Caja.png)

# 1. El potencial en su extremo izquierdo es -1, mientras que en su extremo derecho es 1:
# $$V(-1,y)=-1\qquad ,\qquad V(1,y)=1$$
# 2. El potencial en sus extremos superior e inferior sigue una relación lineal de tal modo que
# $$V(x,-1)=V(x,1)=x$$

# %%
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

#Definition of the relaxation method
def RelaxationJacobi(V, indicesCC, err=1e-7, imax=1000):
    
    diff = 0.; iteracion=0   # Initialize
    V_next = V_old = V.copy()
    nx = np.shape(V)[1]; ny = np.shape(V)[0]
    error = []

    # The while loop implements the Jacobi method
    while True:
        
        # The limits of the for loop take away the edges so each point has neighbors
        for i in range(1, nx-1):
            for j in range(1, ny-1):
                # Points non difined by CC are filtered
                if (i, j) in indicesCC:
                    pass
                else: 
                    tmp= V_old[i, j]
                    # Average
                    V_next[i, j] = (V_old[i+1, j] + V_old[i-1, j] + V_old[i, j-1] + V_old[i, j+1])/4.
                    #print(V_next[i, j], V_old[i, j])
                    # Each point contributes with error, which is summed
                    diff += np.abs( tmp - V_next[i, j])
        diff /= (2* nx +1)**2
        error.append(diff)
        
        iteracion += 1
        if diff< err: # Has the minimum error tolerance been achieved?
            print("Minimum error achieved. Err:", diff)
            break
            
        elif iteracion >= imax: # Has the maximum number of iterations been reached?
            print("Maximum number of iterations reached:", iteracion)
            break
            
        else:
            # Redefinition of arrays, the new is the old in the next iteration
            V_old = V_next.copy()
        
    return V_next, iteracion, diff, error

def PlotVPotential(X, Y, V_potential, title: str):
    # Assuming X, Y, and V_next are already defined in your code
    plt.style.use('default')

    delta = 15 * (X[0][-1] - X[0][0]) / 200

    # 1. Create one wide figure to hold all three plots
    fig = plt.figure(figsize=(15, 5.5))
    fig.suptitle(title, fontsize=16)

    # ---------------------------------------------------------
    # Plot 1: 3D Surface
    # ---------------------------------------------------------
    ax1 = fig.add_subplot(1, 3, 1, projection='3d')
    surf = ax1.plot_surface(X, Y, V_potential, cmap=cm.coolwarm)

    ax1.xaxis.pane.fill = False
    ax1.yaxis.pane.fill = False
    ax1.zaxis.pane.fill = False
    ax1.set_xlabel('x')
    ax1.set_ylabel('y')
    ax1.set_zlabel('V(x, y)')
    ax1.view_init(20, -110)
    ax1.set_title('3D Surface')

    # Attach the colorbar specifically to ax1
    fig.colorbar(surf, ax=ax1, shrink=0.5, aspect=6, location="right")

    # ---------------------------------------------------------
    # Plot 2: Imshow Heatmap
    # ---------------------------------------------------------
    ax2 = fig.add_subplot(1, 3, 2)
    pot = ax2.imshow(V_potential, origin='lower', extent=(X[0][0], X[0][-1], Y[0][0], Y[:][-1][0]), cmap=cm.coolwarm)
    ax2.set_xlim(X[0][0]- delta, X[0][-1] + delta)
    ax2.set_ylim(Y[0][0]- delta, Y[:][-1][0] + delta)
    ax2.set_xlabel('x')
    ax2.set_ylabel('y')
    ax2.set_title('Heatmap')

    # Attach the colorbar specifically to ax2
    fig.colorbar(pot, ax=ax2, shrink=0.8, aspect=10, location="right")

    # ---------------------------------------------------------
    # Plot 3: Contour Plot
    # ---------------------------------------------------------
    ax3 = fig.add_subplot(1, 3, 3)
    cp = ax3.contour(X, Y, V_potential, cmap=cm.coolwarm) # Match the colormap for consistency
    ax3.clabel(cp)
    ax3.set_xlim(X[0][0]- delta, X[0][-1] + delta)
    ax3.set_ylim(Y[0][0]- delta, Y[:][-1][0] + delta)
    ax3.set_xlabel('x')
    ax3.set_ylabel('y')
    ax3.set_title('Equipotential Lines')

    # Clean up spacing so they don't overlap
    plt.tight_layout()
    plt.show()

#Initialize the working ranges for the problem
X = [-1, 1]
Y = [-1, 1]
nx = ny = 20
N = [nx, ny]

# Gird is generated
x = np.linspace(X[0], X[1], N[0])
y = np.linspace(Y[0], Y[1], N[1])
X, Y = np.meshgrid(x, y)
V = np.zeros([N[0], N[1]])

# Boundary conditions are stablished
V0 = -1; V1 = 1
Vx = lambda x: V0 + ((V1 - V0) / (nx-1)) * x   #V(x, 1) = x

indicesCC = []
n = np.shape(V)[1]

for i in range(nx):
    V[i, 0] =  V0          #V(x, -1) = -1
    indicesCC.append((i, 0))
    V[i, n-1] = V1         #V(x, 1 ) =  1
    indicesCC.append((i, n-1))

    V[0, i] = Vx(i)        #V(x, 1) =  x
    indicesCC.append((0, i))
    V[nx-1, i] = Vx(i)     #V(x, -1) = x
    indicesCC.append((n-1, i))

V_next, iteracion, diff, _ = RelaxationJacobi(V, indicesCC)

PlotVPotential(X, Y, V_next, "Square Box")

# %% [markdown]
# Here it is shown that the electric field takes constan values for each position of x-axis inside the box, where each one can be represented by a color or line with the exact value.

# With this information about the electric potential, we can get the electric field by computing the numerical derivative.

# %%
def EField(V_potential):
    # Electric field (x direction)
    nx = len(V_potential[0, :]); ny = len(V_potential[:, 0])
    
    Ex = np.zeros([nx, nx]); Ey = np.zeros([ny, ny])
    # Compute derivatives with finite differences centered
    for i in range(1, nx-1):
        for j in range(1, ny-1):
            Ex[i, j] = -(V_potential[i+1, j] - V_potential[i-1, j])/(2*(2/nx)) 
            Ey[i, j] = -(V_potential[i, j+1] - V_potential[i, j-1])/(2*(2/ny)) 
    
    return Ex, Ey

def PlotEField(x, y, Ex, Ey):
    delta = 15 * (x[-1]-x[0])/200
    color = np.hypot(Ex, Ey) # Color scale
    fig = plt.figure(figsize=(5,5))
    ax = fig.add_subplot(111)
    plt.style.use('default')
    ax.streamplot(x, y, Ey, Ex, color = color, density=1.5)
    ax.set_xlim(x[0]-delta, x[-1]+delta)
    ax.set_ylim(y[0]-delta, y[-1]+delta)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title('Electric Field Lines')
    plt.show()

Ex, Ey = EField(V_next)

x = X[0]
y = Y[:, 0]

PlotEField(x, y, Ex, Ey)

# %% [markdown]
# Where it is shown that the field lines do not change their intensity (color) since the gradient of $x$ is constante, i.e., the field inside the box with two charged edges is constant and begins at the side with positive potential, towards the direction of the side with negative potential.

# ### 2.2 Empty Prism with Metalic Walls and Bar

# Considering an empty prism infinitely large with metal walls and a square transversal section. Inside the prism there is a metal bar with an square tranversal section. The voltage is applied between the bar and the exterior walls, and we want to find the potential between them.

# ![](figures/Prisma.png)

# For this case, the potential at the edges of the bar is fixed at 1, and the exterior walls have potentail set to 0. With this boundary conditions the Jacobi Method can be used to compute the potential.

# %%
#Initialize the working ranges for the problem
X = [-1, 1]
Y = [-1, 1]
nx = ny = 30
N = [nx, ny]
# Gird is generated
x = np.linspace(X[0], X[1], N[0])
y = np.linspace(Y[0], Y[1], N[1])
X, Y = np.meshgrid(x, y)
V = np.zeros([N[0], N[1]])

# Boundary conditions are stablished
l = int(nx/4)
indicesCC = []
for i in range(l, nx -l):
    for j in range(l, nx -l):
        V[i, j]=1
        indicesCC.append((i, j))

V_next, iteracion, diff, _ = RelaxationJacobi(V, indicesCC)

PlotVPotential(X, Y, V_next, "Empty Prism with Bar")

# %% [markdown]
# In this case it is shown that the potential grows from 0 at the external edges of the prism until 1 at the edges of the internal bar. Also, the electric potential takes constant values in a kind of squares with rounded corners, where each one can be represented by a color or a line with exact value.

# %%
Ex, Ey = EField(V_next)

x = X[0]
y = Y[:, 0]

PlotEField(x, y, Ex, Ey)

# %% [markdown]
# Here one can observe that the electric field takes goes from the zones with higher potential (bar edges) to the zones with less potential (external edges). But in this case it is not constant since the gradient of the potential is not as simple as the case of the square box.

# ---

# ### 2.3 Capacitor of Parallel Plates

# A more useful system for real applications is the capacitor made from two parallel plates equally chaged in magnitude but opposite in sign. It is similar to the square box but the restriction over the superior and inferior walls, which gave us the homogeneity of the field, is relaxed.

# %%
#Initialize the working ranges for the problem
X = [-1, 1]
Y = [-1, 1]
nx = ny = 20
N = [nx, ny]

# Gird is generated
x = np.linspace(X[0], X[1], N[0])
y = np.linspace(Y[0], Y[1], N[1])
X, Y = np.meshgrid(x, y)
V = np.zeros([N[0], N[1]])

# Boundary conditions are stablished
l = int(nx/4)
indicesCC = []
for i in range(l, nx -l):
    V[i, l]= -1
    indicesCC.append((i, l))
    V[i, nx-l-1] = 1
    indicesCC.append((i, nx-l-1))

V_next, iteracion, diff, error_jacobi = RelaxationJacobi(V, indicesCC)

PlotVPotential(X, Y, V_next, "Capacitor of Parallel Plates")

# %% [markdown]
# Here it is shown that the electric potentail takes constant values in a kind of ellipses that become rectangular with rounded corners, where each one can be represented by a color or by a line with an exact value.

# %%
Ex, Ey = EField(V_next)

x = X[0]
y = Y[:, 0]

PlotEField(x, y, Ex, Ey)

# %% [markdown]
# And the field, again, goes from the region with higher potential (right plate) to the region with lower potential (left plate). But in this case the field lines algo come from infinity to the plate on the left and extend to infinity from the plate to the right.

# ---

# ### 2.4 Convergence of Jacobi's Method

# Unfortunately, Jacobi's method of relaxation does not count with good convergence properties.

# Turns out that, when applied to a problem in the plane, for example to a $L\times L$ grid, the number of iterations required to reach convergence is of the order of $L^2$. This is bad because if we augment the number of points by a factor of 2, convergence will require 4 times more iterations.

# #### 2.4.1 Gauss-Seidel Method

# A modest upgrade is made accomplished through the Gauss-Seidel method, which uses a different way to iterate over the grid of points, taking into consideration the new information computed for the current iteration $n+1$ as follows:

# $$V_{n+1}(i,j)=\frac{1}{4}\left[V_{n}(i+1,j) +V_{n+1}(i-1,j)+ V_{n}(i,j+1)+V_{n+1}(i,j-1) \right]$$

# Even though there is an upgrade in performance, it only reduces the required iterations by a factor of 2.

# %%
#Definition of the relaxation method
def RelaxationGS(V, indicesCC, err=1e-7, imax=1000):
    
    diff = 0.; iteracion=0   # Initialize
    V_next = V_old = V.copy()
    nx = np.shape(V)[1]; ny = np.shape(V)[0]
    error = []

    # The while loop implements the Jacobi method
    while True:
        
        # The limits of the for loop take away the edges so each point has neighbors
        for i in range(1, nx-1):
            for j in range(1, ny-1):
                # Points non difined by CC are filtered
                if (i, j) in indicesCC:
                    pass
                else: 
                    tmp= V_old[i, j]
                    # Average
                    V_next[i, j] = (V_next[i+1, j] + V_next[i-1, j] + V_next[i, j+1] + V_next[i, j-1])/4.
                    #print(V_next[i, j], V_old[i, j])
                    # Each point contributes with error, which is summed
                    diff += np.abs( tmp - V_next[i, j])
        diff /= (2* nx +1)**2
        error.append(diff)
        
        iteracion += 1
        if diff< err: # Has the minimum error tolerance been achieved?
            print("Minimum error achieved. Err:", diff)
            break
            
        elif iteracion >= imax: # Has the maximum number of iterations been reached?
            print("Maximum number of iterations reached:", iteracion)
            break
            
        else:
            # Redefinition of arrays, the new is the old in the next iteration
            V_old = V_next.copy()
        
    return V_next, iteracion, diff, error

V_next, iteracion, diff, error_gs = RelaxationGS(V, indicesCC)

PlotVPotential(X, Y, V_next, "Capacitor of Parallel Plates")

# %% [markdown]
# #### 2.4.2 Successive Over-Relaxation (SOR)

# Let $V^* (i, j)$ be the computed value by Jacobi's (or Gauss-Seidel) method, we can think of the quantity

# $$\Delta V(i, j) = V^*(i, j) - V_{n}(i, j)$$

# as the change recommended by Jacobi's (or Gauss-Seidel) method. This quantity is very conservative, such that to accelerate the convergence we can change the potential for

# $$V_{n+1}(i, j) =  \alpha \Delta(i, j) + V_{n}(i, j)$$

# where $\alpha$ is a factor that measure how much to over-relax:

# * $\alpha = 1 \qquad \implies$ Jacobi's Method

# * $\alpha\geq 2 \qquad \implies $ No convergence

# * $\alpha \in [1, 2] \qquad \implies$ Over-Relaxation

# The goal is to determine $\alpha$ such that a greater convergence is achieved, this value depends on the chosen geometry, but for an square grid the best choice is

# $$\alpha \approx \dfrac{2}{1 + \pi/L}$$

# This method makes the number of iterations of the order of $L$.

# %%
#Definition of the relaxation method
def RelaxationSOR(V, indicesCC, err=1e-7, imax=1000):
    
    errores=[]; iteracion=0   # Initialize
    V_next = V_GS= V.copy()
    ny, nx = np.shape(V)
    alpha = 2/(1 + np.pi/nx)
    error_list = []

    # The while loop implements the Jacobi method
    while True:
        
        # The limits of the for loop take away the edges so each point has neighbors
        for i in range(1, nx-1):
            for j in range(1, ny-1):
                # Points non difined by CC are filtered
                if (i, j) in indicesCC:
                    pass
                else: 
                    tmp = V_next[i, j]
                    V_GS = (V_next[i+1, j] + V_next[i-1, j] + V_next[i, j+1] + V_next[i, j-1])/4. # Gauss-Seidel
                    ajuste = alpha*(V_GS - tmp) # Adjustment by SOR method
                    V_next[i, j] = ajuste + tmp  # SOR
                    # Error by point is saved
                    error =abs(1 - V_GS/(V_next[i,j]+1e-12))
                    errores.append(error)
        
        errmax = max(errores)
        error_list.append(errmax)
        iteracion += 1
        if errmax < err: # Has the minimum error tolerance been achieved?
            print("Minimum error achieved. Err:", errmax)
            print("Iteration: ", iteracion)
            break
            
        elif iteracion >= imax: # Has the maximum number of iterations been reached?
            print("Maximum number of iterations reached:", iteracion)
            break
            
        else:
            # Restart
            errores = []
        
    return V_next, iteracion, diff, error_list

V_next, iteracion, diff, error_sor = RelaxationSOR(V, indicesCC)

PlotVPotential(X, Y, V_next, "Capacitor of Parallel Plates")

# %%
plt.style.use('default')
fig, ax= plt.subplots(1,3, figsize=(17, 4))

ax[0].plot(error_jacobi)
ax[1].plot(error_gs)
ax[2].plot(error_sor)
for i in [0,1,2]:
    ax[i].set_xlabel('Iteration')
    ax[i].set_ylabel('Approximate Error')
    
ax[0].set_title('Jacobi')
ax[1].set_title('Gauss-Seidel')
ax[2].set_title('Over-Relaxed')

plt.show()

# %% [markdown]
# ---

# ## 3. Poisson's Equation

# The next step is to compute the potentials and fields in regions near charges, where the differential Gauss Law takes the form

# $$\vec{\nabla}\cdot \vec{E}(x,y,z)= \frac{\partial E_x}{\partial x} + \frac{\partial E_y}{\partial y} + \frac{\partial E_z}{\partial z}=\frac{\rho}{\epsilon_0}$$

# And we know that the electric field is the gradient of the electric potential. Which tells us that the electric potential obeys Poisson's Equation

# $$\vec{\nabla}^2V = \frac{\partial^2V}{\partial x^2} + \frac{\partial^2V}{\partial y^2} + \frac{\partial^2V}{\partial z^2}=-\frac{\rho}{\epsilon_0}$$

# where $\rho$ is the charge density and $\epsilon_0$ is the electric permitivity constant. The computational methods are similar, only a term for the charge density is added. For example, Jacobi's methos would be

# $$\begin{aligned}
#     V(i,j,k)= & \frac{1}{6}[V(i+1,j,k)+V(i-1,j,k) +V(i,j+1,k) +V(i,j-1,k) \\ &  +V(i,j,k+1)+V(i,j,k-1)] +\frac{\rho(i,j,k)(\Delta x)^2}{6\epsilon_0}
# \end{aligned}$$

# where the charge density, in general, is a function of the position.

# ### 3.1 Point Charge

# Considering a situation in which

# $$\rho=\left\{ \begin{array}{ll}
#     1, & x=y=0 \\
#     0, & \text{en otro caso}
# \end{array} \right.$$

# a code similar to those for Laplace equation can be developed.

# %%
#Definition of the relaxation method
def SOR_Poisson2D(V, indicesCC, rho, err=1e-7, imax=1000):
    errores=[]; iteracion=0   # Initialize
    V_next = V_GS= V.copy()
    ny, nx = np.shape(V)
    alpha = 1
    error_list = []

    def NeighbourAverage(V, i, j):
        a = (V[i+1, j] + V[i-1, j] + V[i, j+1] + V[i, j-1])/4.
        return a

    # The while loop implements the Jacobi method
    while True:
        
        # The limits of the for loop take away the edges so each point has neighbors
        for i in range(1, nx-1):
            for j in range(1, ny-1):
                # Points non difined by CC are filtered
                if (i, j) in indicesCC:
                    pass
                else: 
                    tmp = V_next[i, j]
                    V_GS = NeighbourAverage(V_next, i, j) +  rho(i, j)/4.  #Gauss-Seidel
                    ajuste = alpha*(V_GS - tmp) # Adjustment by SOR method
                    V_next[i, j] = ajuste + tmp  # SOR
                    # Error by point is saved
                    error =abs(1 - V_GS/(V_next[i,j]+1e-12))
                    errores.append(error)
        
        errmax = max(errores)
        error_list.append(errmax)
        iteracion += 1
        if errmax < err: # Has the minimum error tolerance been achieved?
            print("Minimum error achieved. Err:", errmax)
            print("Iteration: ", iteracion)
            break
            
        elif iteracion >= imax: # Has the maximum number of iterations been reached?
            print("Maximum number of iterations reached:", iteracion)
            break
            
        else:
            # Restart
            errores = []
        
    return V_next, iteracion, diff, error_list

#Initialize the working ranges for the problem
X = [-0.2, 0.2]
Y = [-0.2, 0.2]
nx = ny = 50
N = [nx, ny]

# Gird is generated
x = np.linspace(X[0], X[1], N[0])
y = np.linspace(Y[0], Y[1], N[1])
X, Y = np.meshgrid(x, y)
V = np.zeros([N[0], N[1]])

def rho(i, j):
    return 1 if (i, j)==(nx/2, ny/2) else 0

# Boundary conditions are stablished
nx = np.shape(V)[0]
indicesCC = []

V_next, iteracion, diff, _ = SOR_Poisson2D(V, indicesCC, rho)

PlotVPotential(X, Y, V_next, "Point charge")

# %% [markdown]
# In this case, it is observed that the potential forms a very sharp peak right at the location of the point charge and decreases rapidly to zero as we move away in any direction.

# It is also shown that the electric potential takes constan values in cicular concentric paths, except for the area near the initially proposed frontier. This is a problem of the simmetry with which the code is based, since square grids are the bases to compute the potential. If we wanted to do the code to converge more quickly and for it to be more realistic, we should change the grid to one with circular simmetry, since the Coulomb's potential produced by a point charge is a central potential.

# %%
Ex, Ey = EField(V_next)

x = X[0]
y = Y[:, 0]

PlotEField(x, y, Ex, Ey)

# %% [markdown]
# For the electric field, it is shown that the field lines start at the center where the potential is higher, and flow towards infinity in all directions where the potential is zero.

# ---

# # 2. Magnetic Fields

# Magnetic fields are produced around moving charges (currents or point charges). The simplest case is that of a steady current $I$ in a straight wire with a segment $d\vec{z}$. The magnetic field is obtained through the Biot-Savart Law

# $$d\vec{B}=\frac{\mu_0I}{4\pi} \frac{d\vec{z}\times\vec{z}}{r^3}$$

# where $\vec{r}$ is the vector pointing from the current-carrying segment to the point in question, and $\mu_0$ is the magnetic permeability of free space.

# ![](figures/Corriente_Cable.png)

# For this type of geometry, the cross product can be expressed in terms of the angle $\theta$ between $d\vec{z}$ and $\vec{r}$:

# $$dB=\frac{\mu_0I}{4\pi}\frac{dz\sin{\theta}}{r^2}$$

# The total field is the integral of $dB$ over the entire length of the wire. However, numerically, the integral cannot be performed directly; instead, a discrete sum of values is used by taking small intervals $dz\mapsto\Delta z$. That is, the field is:

# $$B\approx\sum_i\frac{\mu_0I}{4\pi}\frac{x\Delta z}{(z_i^2+x^2)^{3/2}}$$

# Various methods exist to improve the convergence and precision of numerical integrals, such as Simpson's Rule. As before, reducing the spacing size $\Delta z$ improves the results of the method.

# In this case, if the wire is infinitely long, the field is $B = \mu_0 I / (2\pi r)$.

# ## 2.1 Magnetic Dipole

# As is known from Gauss's Law for magnetism, magnetic monopoles do not exist in nature; the trajectories followed by magnetic field lines are always closed loops.


# However, magnetic multipoles do exist, with the dipole being the simplest. It possesses a "north" from which field lines emerge and a "south" toward which field lines are directed.

# In Python, using a code similar to the one used for electric potential, a magnetic dipole can be found numerically. This is because the magnetic field has the characteristic of rotating around its sources (moving charges or steady electric currents), distributing itself in space in a manner similar to the equipotential surfaces of an electric field.

# %%
def plot_map_phase_space():
    x, y = np.meshgrid(np.arange(-5., 5., 0.01), np.arange(-5., 5., 0.01))
    xdot, ydot =0, 0
    for i in range(len(xq)):
        norm = np.sqrt((x-xq[i])**2 + (y-yq[i])**2)
        xdot += -q[i]*(y-yq[i])/(norm**3)
        ydot += q[i]*(x-xq[i])/(norm**3)
        if q[i]>0:
            circle=plt.Rectangle((yq[i]-de,xq[i]-de), width=2*de, height=3*de, color='blue')
            ax.text(yq[i]-de,xq[i]-de, 'S', fontsize=12, va='bottom',color='white')
        else:
            circle=plt.Rectangle((yq[i]-de, xq[i]-2*de), width=2*de, height=3*de, color='red')
            ax.text(yq[i]-de, xq[i]-2*de, 'N', fontsize=12, va='bottom',color='white')
        ax.add_artist(circle)

    ax.streamplot(x, y, xdot, ydot, density=0.7, linewidth=1.6)
    ax.set_xlabel(r"x")
    ax.set_ylabel(r"y")

fig, ax = plt.subplots(1,1, figsize=(3, 3))
xq=[-0.6,0.6]
yq=[0,0]
q=[1,-1]
de=0.3
plot_map_phase_space()
plt.show()